function [sfx, info] = myShapeFromContour(labeldata, display)
    param_string = ['params.SOLVE_ALBEDO = 0;', ...
                    'params.SOLVE_LIGHT = 0;', ...
                    'params.USE_SELF_OCCLUSION = 0;', ...
                    'params.USE_SHARP_BDRY = 0;', ...
                    'params.MULT_OPTS.saifs.height.fold = { 0.0 };', ...
                    'params.MULT_OPTS.saifs.height.hinge = { 0.0 };', ...                    
                    'params.MULT_OPTS.saifs.height.contour = { 3.3636 };', ...
                    'params.MULT_OPTS.saifs.height.slant = { 0.2973 };', ...
                    'params.MULT_OPTS.saifs.height.smooth = { 1024 };'];
    if(~exist('display','var'))
        display = false;
    end
    [sfx, info] = myShapeFromX(param_string, labeldata, display);
end
